name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs: 
  playwrighttests:
    run-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.57.0-focal
      env:
        ADMIN_PASSWORD: ${{ secrects.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: run tests
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test: ci